"""AI review pipeline for PDF2BOOK (Markdown-based).

This package implements the Markdown-based AI review that runs after
``book.md`` and ``meta.md`` have been generated by the rule-based
postprocessing. The AI sees the actual Markdown structure that will
become the EPUB and fixes issues the rules couldn't handle.

Flow:
  1. **Collect** — `markdown_review.collect_markdown_issues` scans
     ``book.md`` line by line for low-confidence blocks, chapter titles
     with issues (OCR garbled / split / too short), and current metadata.
  2. **Constrain** — `constraints.extract_constraints` derives hard
     limits (max_length, preserved_chars, max_edit_distance) from each
     low-confidence text; `validate_correction` checks AI corrections.
  3. **Prompt** — `markdown_review.build_review_prompt` builds a single
     comprehensive prompt containing all issues with context.
  4. **Call + Apply** — `ai_client.AIClient.review_markdown` calls the
     API and `markdown_review.apply_markdown_corrections` writes the
     corrections back to ``book.md`` (by line number) and ``meta.md``.

When `AIReviewConfig.enabled=False`, the client short-circuits and the
pipeline runs without AI (low-confidence texts keep their
``>[low-confidence]`` markers for manual proofreading).
"""

from __future__ import annotations

from pdf2book.review.ai_client import AIClient
from pdf2book.review.constraints import (
    CorrectionConstraints,
    extract_constraints,
    validate_correction,
)
from pdf2book.review.markdown_review import (
    apply_markdown_corrections,
    build_review_prompt,
    collect_markdown_issues,
)

__all__ = [
    # Markdown review
    "collect_markdown_issues",
    "build_review_prompt",
    "apply_markdown_corrections",
    # Constraints (preserved)
    "CorrectionConstraints",
    "extract_constraints",
    "validate_correction",
    # AI client
    "AIClient",
]
