"""CLI entry point for pdf2book.

Three subcommands:

  ``ocr`` — Stage 1: PDF -> OCR -> postprocess -> work_dir/book.md + meta.md
            Use this to generate a previewable Markdown; edit it, then run
            ``epub`` to build the final EPUB.

  ``epub`` — Stage 2: Markdown + meta.md -> .epub via Pandoc
             Reads metadata from a sibling ``meta.md`` (or ``--meta``).

  ``convert`` — One-shot: ``ocr`` + ``epub`` chained (backward compat).

Usage::

    pdf2book ocr input.pdf [--resume] [--config config.yaml] [-v]
    pdf2book epub work_dir/book.md -o out.epub [--meta meta.md] [--cover c.jpg] [-v]
    pdf2book convert input.pdf -o out.epub [--resume] [--config config.yaml] [-v]
"""

from __future__ import annotations

from pathlib import Path

import typer

from pdf2book.config import AppConfig
from pdf2book.pipeline import ConversionPipeline
from pdf2book.utils.logger import setup_logger

app = typer.Typer(
    name="pdf2book",
    help="Convert scanned PDF books to Kindle-friendly EPUB via OCR.",
    no_args_is_help=True,
)


@app.callback()
def _main() -> None:
    """pdf2book — PDF to Kindle EPUB converter.

    The callback forces subcommand mode so the CLI is always invoked as
    ``pdf2book <subcommand> ...`` (otherwise Typer flattens a single-command
    app and drops the subcommand name).
    """


@app.command()
def ocr(
    pdf: Path = typer.Argument(..., help="Input scanned PDF path", exists=True),
    resume: bool = typer.Option(False, "--resume", help="Resume from cache (skip OCR'd pages)"),
    config: Path | None = typer.Option(None, "--config", help="Config YAML path"),
    verbose: bool = typer.Option(False, "-v", "--verbose", help="Enable DEBUG logging"),
) -> None:
    """Stage 1: PDF -> OCR -> Markdown (previewable).

    Generates ``work_dir/book.md`` and ``work_dir/meta.md``. Preview or edit
    the Markdown, then run ``pdf2book epub`` to build the EPUB.
    """
    cfg = AppConfig.load(config) if config else AppConfig.default()
    log = setup_logger("DEBUG" if verbose else "INFO")

    pipeline = ConversionPipeline(cfg, log)
    book_md = pipeline.run_to_markdown(pdf, resume=resume)
    typer.echo(f"Markdown written: {book_md}")
    typer.echo(f"Metadata written: {book_md.parent / 'meta.md'}")
    typer.echo("Preview the Markdown, then run:")
    typer.echo(f"  pdf2book epub {book_md} -o output.epub")


@app.command()
def epub(
    markdown: Path = typer.Argument(..., help="Input Markdown path (from `ocr` stage)", exists=True),
    output: Path = typer.Option(..., "-o", "--output", help="Output EPUB path"),
    meta: Path | None = typer.Option(None, "--meta", help="Metadata YAML path (default: sibling meta.md)"),
    cover: Path | None = typer.Option(None, "--cover", help="Cover image path", exists=True),
    css: Path | None = typer.Option(None, "--css", help="CSS stylesheet path", exists=True),
    config: Path | None = typer.Option(None, "--config", help="Config YAML path"),
    verbose: bool = typer.Option(False, "-v", "--verbose", help="Enable DEBUG logging"),
) -> None:
    """Stage 2: Markdown -> EPUB via Pandoc.

    Reads metadata from a sibling ``meta.md`` (generated by ``ocr``) or from
    ``--meta``. Use ``--cover`` and ``--css`` to customize the EPUB.
    """
    cfg = AppConfig.load(config) if config else AppConfig.default()
    log = setup_logger("DEBUG" if verbose else "INFO")

    output.parent.mkdir(parents=True, exist_ok=True)

    pipeline = ConversionPipeline(cfg, log)
    out = pipeline.build_epub(markdown, output, meta_path=meta, cover=cover, css=css)
    typer.echo(f"Done: {out}")


@app.command()
def convert(
    pdf: Path = typer.Argument(..., help="Input scanned PDF path", exists=True),
    output: Path = typer.Option(..., "-o", "--output", help="Output EPUB path"),
    resume: bool = typer.Option(False, "--resume", help="Resume from cache (skip OCR'd pages)"),
    config: Path | None = typer.Option(None, "--config", help="Config YAML path"),
    cover: Path | None = typer.Option(None, "--cover", help="Cover image path", exists=True),
    verbose: bool = typer.Option(False, "-v", "--verbose", help="Enable DEBUG logging"),
) -> None:
    """One-shot: PDF -> OCR -> Markdown -> EPUB (``ocr`` + ``epub`` chained).

    Equivalent to running ``ocr`` then ``epub`` without previewing the
    intermediate Markdown.
    """
    cfg = AppConfig.load(config) if config else AppConfig.default()
    log = setup_logger("DEBUG" if verbose else "INFO")

    output.parent.mkdir(parents=True, exist_ok=True)

    pipeline = ConversionPipeline(cfg, log)
    out = pipeline.run(pdf, output, resume=resume, cover=cover)
    typer.echo(f"Done: {out}")


if __name__ == "__main__":
    app()
